module.exports = [
  // GENERAL KNOWLEDGE (GK)
  { id: 1, category: "GK", question: "What is the capital of Japan?", options: ["Seoul", "Tokyo", "Beijing", "Bangkok"], answer: "Tokyo" },
  { id: 2, category: "GK", question: "Which is the largest ocean on Earth?", options: ["Atlantic Ocean", "Indian Ocean", "Pacific Ocean", "Arctic Ocean"], answer: "Pacific Ocean" },
  { id: 3, category: "GK", question: "Which planet is known as the Red Planet?", options: ["Venus", "Mars", "Jupiter", "Saturn"], answer: "Mars" },
  { id: 4, category: "GK", question: "What is the largest country in the world by land area?", options: ["Canada", "China", "United States", "Russia"], answer: "Russia" },
  { id: 5, category: "GK", question: "How many bones are there in an adult human body?", options: ["106", "206", "306", "406"], answer: "206" },
  { id: 6, category: "GK", question: "Which is the tallest mountain in the world?", options: ["K2", "Mount Everest", "Mount Kilimanjaro", "Mount Fuji"], answer: "Mount Everest" },
  { id: 7, category: "GK", question: "Which country is home to the Kangaroo?", options: ["South Africa", "Australia", "New Zealand", "Austria"], answer: "Australia" },
  { id: 8, category: "GK", question: "Which country has the largest population in the world?", options: ["India", "China", "United States", "Indonesia"], answer: "India" },
  { id: 9, category: "GK", question: "Which animal is known as the 'Ship of the Desert'?", options: ["Horse", "Camel", "Donkey", "Elephant"], answer: "Camel" },
  { id: 10, category: "GK", question: "In which year did the Titanic sink?", options: ["1905", "1912", "1920", "1936"], answer: "1912" },
  { id: 11, category: "GK", question: "What is the hardest natural substance on Earth?", options: ["Gold", "Iron", "Diamond", "Platinum"], answer: "Diamond" },
  { id: 12, category: "GK", question: "How many continents are there in the world?", options: ["5", "6", "7", "8"], answer: "7" },
  { id: 13, category: "GK", question: "Which language has the most native speakers?", options: ["English", "Spanish", "Mandarin", "Hindi"], answer: "Mandarin" },
  { id: 14, category: "GK", question: "Who painted the Mona Lisa?", options: ["Vincent van Gogh", "Pablo Picasso", "Leonardo da Vinci", "Michelangelo"], answer: "Leonardo da Vinci" },
  { id: 15, category: "GK", question: "What is the smallest country in the world?", options: ["Monaco", "Vatican City", "San Marino", "Liechtenstein"], answer: "Vatican City" },

  // MOVIES & CINEMA
  { id: 101, category: "Movies", question: "Who directed the movie 'Inception'?", options: ["Steven Spielberg", "Christopher Nolan", "Quentin Tarantino", "James Cameron"], answer: "Christopher Nolan" },
  { id: 102, category: "Movies", question: "Which movie won the Oscar for Best Picture in 2020?", options: ["1917", "Joker", "Parasite", "Once Upon a Time in Hollywood"], answer: "Parasite" },
  { id: 103, category: "Movies", question: "Which actor played Iron Man in the Marvel Cinematic Universe?", options: ["Chris Evans", "Robert Downey Jr.", "Chris Hemsworth", "Mark Ruffalo"], answer: "Robert Downey Jr." },
  { id: 104, category: "Movies", question: "Which is the highest-grossing film of all time?", options: ["Titanic", "Avengers: Endgame", "Avatar", "Star Wars: The Force Awakens"], answer: "Avatar" },
  { id: 105, category: "Movies", question: "What is the name of the fictional African country in 'Black Panther'?", options: ["Zamunda", "Wakanda", "Genovia", "Latveria"], answer: "Wakanda" },
  { id: 106, category: "Movies", question: "In 'The Matrix', what pill does Neo take?", options: ["Blue", "Red", "Green", "Yellow"], answer: "Red" },
  { id: 107, category: "Movies", question: "Who played the Joker in 'The Dark Knight' (2008)?", options: ["Jared Leto", "Joaquin Phoenix", "Heath Ledger", "Jack Nicholson"], answer: "Heath Ledger" },
  { id: 108, category: "Movies", question: "What is the first rule of Fight Club?", options: ["Always win", "Never talk about Fight Club", "Bring your own gloves", "No shirts, no shoes"], answer: "Never talk about Fight Club" },
  { id: 109, category: "Movies", question: "Which movie features the quote 'May the Force be with you'?", options: ["Star Trek", "Harry Potter", "Star Wars", "Lord of the Rings"], answer: "Star Wars" },
  { id: 110, category: "Movies", question: "Who is the villain in Avengers: Infinity War?", options: ["Loki", "Ultron", "Thanos", "Kang"], answer: "Thanos" },
  { id: 111, category: "Movies", question: "What is the name of the hobbit who destroys the One Ring?", options: ["Sam", "Merry", "Pippin", "Frodo"], answer: "Frodo" },
  { id: 112, category: "Movies", question: "Which Disney movie features the song 'Let It Go'?", options: ["Tangled", "Moana", "Frozen", "Brave"], answer: "Frozen" },
  { id: 113, category: "Movies", question: "What is the highest-grossing animated movie of all time?", options: ["The Lion King", "Frozen II", "Inside Out 2", "Toy Story 4"], answer: "Inside Out 2" },
  { id: 114, category: "Movies", question: "Who directed 'Jurassic Park'?", options: ["James Cameron", "Steven Spielberg", "George Lucas", "Ridley Scott"], answer: "Steven Spielberg" },
  { id: 115, category: "Movies", question: "In which movie does Tom Hanks play a man stranded on an island?", options: ["Forrest Gump", "Cast Away", "Apollo 13", "The Terminal"], answer: "Cast Away" },

  // GAMING
  { id: 201, category: "Gaming", question: "What is the best-selling video game of all time?", options: ["Minecraft", "GTA V", "Tetris", "Wii Sports"], answer: "Minecraft" },
  { id: 202, category: "Gaming", question: "In Minecraft, which block is required to build a Nether Portal?", options: ["Obsidian", "Bedrock", "Netherrack", "Glowstone"], answer: "Obsidian" },
  { id: 203, category: "Gaming", question: "What is the name of the main protagonist in 'The Legend of Zelda' series?", options: ["Zelda", "Link", "Ganon", "Mario"], answer: "Link" },
  { id: 204, category: "Gaming", question: "Which gaming console is developed by Sony?", options: ["PlayStation", "Xbox", "Switch", "Genesis"], answer: "PlayStation" },
  { id: 205, category: "Gaming", question: "What popular battle royale game features 100 players jumping from a battle bus?", options: ["PUBG", "Fortnite", "Apex Legends", "Call of Duty"], answer: "Fortnite" },
  { id: 206, category: "Gaming", question: "What color is Pac-Man?", options: ["Yellow", "Red", "Blue", "Green"], answer: "Yellow" },
  { id: 207, category: "Gaming", question: "Who is Mario's brother?", options: ["Wario", "Luigi", "Bowser", "Toad"], answer: "Luigi" },
  { id: 208, category: "Gaming", question: "Which game features a continent called Tamriel?", options: ["World of Warcraft", "The Elder Scrolls", "The Witcher", "Dragon Age"], answer: "The Elder Scrolls" },
  { id: 209, category: "Gaming", question: "In GTA San Andreas, what is the main character's name?", options: ["Nico Bellic", "Tommy Vercetti", "Carl Johnson (CJ)", "Franklin"], answer: "Carl Johnson (CJ)" },
  { id: 210, category: "Gaming", question: "What is the highest rank in Valorant?", options: ["Global Elite", "Radiant", "Predator", "Grandmaster"], answer: "Radiant" },
  { id: 211, category: "Gaming", question: "Which company developed 'Genshin Impact'?", options: ["Tencent", "NetEase", "HoYoverse", "Square Enix"], answer: "HoYoverse" },
  { id: 212, category: "Gaming", question: "In 'Among Us', what are the bad guys called?", options: ["Aliens", "Impostors", "Traitors", "Killers"], answer: "Impostors" },
  { id: 213, category: "Gaming", question: "Which game won Game of the Year in 2022?", options: ["God of War Ragnarok", "Elden Ring", "Horizon Forbidden West", "Stray"], answer: "Elden Ring" },
  { id: 214, category: "Gaming", question: "What is the most popular game mode in League of Legends?", options: ["ARAM", "Summoner's Rift", "TFT", "Nexus Blitz"], answer: "Summoner's Rift" },
  { id: 215, category: "Gaming", question: "What is the main weapon of Master Chief in Halo?", options: ["Lancer", "Assault Rifle", "Plasma Pistol", "Energy Sword"], answer: "Assault Rifle" },

  // TECH
  { id: 301, category: "Tech", question: "Who is the co-founder of Microsoft alongside Bill Gates?", options: ["Paul Allen", "Steve Jobs", "Elon Musk", "Larry Page"], answer: "Paul Allen" },
  { id: 302, category: "Tech", question: "Which programming language is mainly used for Android App Development?", options: ["Swift", "Kotlin", "Python", "Ruby"], answer: "Kotlin" },
  { id: 303, category: "Tech", question: "What does HTTP stand for?", options: ["Hypertext Transfer Protocol", "Hypertext Terminal Program", "High Transfer Tech Protocol", "Hyperlink Transfer Text Program"], answer: "Hypertext Transfer Protocol" },
  { id: 304, category: "Tech", question: "Which tech company created the iPhone?", options: ["Samsung", "Google", "Apple", "Microsoft"], answer: "Apple" },
  { id: 305, category: "Tech", question: "What is the most popular search engine globally?", options: ["Yahoo", "Bing", "Google", "DuckDuckGo"], answer: "Google" },
  { id: 306, category: "Tech", question: "What does WiFi stand for?", options: ["Wireless Fidelity", "Wire Free", "Wireless Fiber", "None of these (It's a made-up brand name)"], answer: "None of these (It's a made-up brand name)" },
  { id: 307, category: "Tech", question: "Who is the CEO of Tesla and SpaceX?", options: ["Jeff Bezos", "Bill Gates", "Elon Musk", "Mark Zuckerberg"], answer: "Elon Musk" },
  { id: 308, category: "Tech", question: "What does HTML stand for?", options: ["Hyper Text Markup Language", "High Tech Modern Language", "Hyperlinks and Text Markup Language", "Home Tool Markup Language"], answer: "Hyper Text Markup Language" },
  { id: 309, category: "Tech", question: "Which company bought GitHub in 2018?", options: ["Google", "Microsoft", "Amazon", "Facebook"], answer: "Microsoft" },
  { id: 310, category: "Tech", question: "What is the main language used for styling web pages?", options: ["HTML", "JavaScript", "Python", "CSS"], answer: "CSS" },
  { id: 311, category: "Tech", question: "Which operating system is open-source?", options: ["Windows", "macOS", "Linux", "iOS"], answer: "Linux" },
  { id: 312, category: "Tech", question: "What does GPU stand for?", options: ["General Processing Unit", "Graphics Processing Unit", "Gaming Performance Unit", "Graphical Performance Utility"], answer: "Graphics Processing Unit" },
  { id: 313, category: "Tech", question: "Which social media app is famous for short-form video content?", options: ["Facebook", "LinkedIn", "TikTok", "Pinterest"], answer: "TikTok" },
  { id: 314, category: "Tech", question: "What does 'RAM' stand for in a computer?", options: ["Random Access Memory", "Read Access Memory", "Run All Memory", "Random Allocation Memory"], answer: "Random Access Memory" },
  { id: 315, category: "Tech", question: "Who is the creator of the Python programming language?", options: ["Linus Torvalds", "Guido van Rossum", "Dennis Ritchie", "James Gosling"], answer: "Guido van Rossum" },

  // ANIME & MANGA
  { id: 401, category: "Anime", question: "In 'Naruto', who is the Nine-Tailed Beast sealed inside Naruto?", options: ["Kurama", "Gyuki", "Shukaku", "Matatabi"], answer: "Kurama" },
  { id: 402, category: "Anime", question: "Which anime features a notebook that can kill people?", options: ["Attack on Titan", "Death Note", "Demon Slayer", "One Piece"], answer: "Death Note" },
  { id: 403, category: "Anime", question: "What is the name of Luffy's signature straw hat crew in 'One Piece'?", options: ["Straw Hat Pirates", "Red Hair Pirates", "Heart Pirates", "Blackbeard Pirates"], answer: "Straw Hat Pirates" },
  { id: 404, category: "Anime", question: "Who is the main character in the anime 'Dragon Ball Z'?", options: ["Vegeta", "Gohan", "Goku", "Piccolo"], answer: "Goku" },
  { id: 405, category: "Anime", question: "In 'Demon Slayer', what is the name of Tanjiro's sister?", options: ["Nezuko", "Shinobu", "Kanao", "Mitsuri"], answer: "Nezuko" },
  { id: 406, category: "Anime", question: "What is the highest-grossing anime film of all time?", options: ["Spirited Away", "Your Name", "Demon Slayer: Mugen Train", "Suzume"], answer: "Demon Slayer: Mugen Train" },
  { id: 407, category: "Anime", question: "In 'Attack on Titan', what are the giant humanoid creatures called?", options: ["Goliaths", "Titans", "Colossus", "Giants"], answer: "Titans" },
  { id: 408, category: "Anime", question: "Which anime is about a boy who becomes a hero without a Quirk?", options: ["One Punch Man", "My Hero Academia", "Black Clover", "Jujutsu Kaisen"], answer: "My Hero Academia" },
  { id: 409, category: "Anime", question: "Who wrote 'Death Note'?", options: ["Akira Toriyama", "Tsugumi Ohba", "Eiichiro Oda", "Masashi Kishimoto"], answer: "Tsugumi Ohba" },
  { id: 410, category: "Anime", question: "In 'Jujutsu Kaisen', who is the strongest sorcerer?", options: ["Yuji Itadori", "Megumi Fushiguro", "Satoru Gojo", "Sukuna"], answer: "Satoru Gojo" },
  { id: 411, category: "Anime", question: "What is the name of the protagonist in 'Bleach'?", options: ["Naruto", "Ichigo Kurosaki", "Luffy", "Sasuke"], answer: "Ichigo Kurosaki" },
  { id: 412, category: "Anime", question: "In 'Tokyo Ghoul', what is Kaneki Ken's hair color after torture?", options: ["Black", "White", "Red", "Blonde"], answer: "White" },
  { id: 413, category: "Anime", question: "What is the power system used in 'Hunter x Hunter'?", options: ["Chakra", "Ki", "Nen", "Haki"], answer: "Nen" },
  { id: 414, category: "Anime", question: "Who is the main villain in 'JoJo's Bizarre Adventure: Stardust Crusaders'?", options: ["Kars", "Yoshikage Kira", "Dio Brando", "Diavolo"], answer: "Dio Brando" },
  { id: 415, category: "Anime", question: "In 'Sword Art Online', what is Kirito's real name?", options: ["Kazuto Kirigaya", "Kiyotaka Ayanokoji", "Ken Kaneki", "Kousei Arima"], answer: "Kazuto Kirigaya" },

  // MEMES & CULTURE
  { id: 501, category: "Memes", question: "What is the name of the green frog meme that became popular on the internet?", options: ["Kermit", "Pepe", "Dat Boi", "Slippy"], answer: "Pepe" },
  { id: 502, category: "Memes", question: "Complete the famous meme: 'Keep Calm and...'", options: ["Carry On", "Code On", "Go Party", "Stay Home"], answer: "Carry On" },
  { id: 503, category: "Memes", question: "In the 'Distracted Boyfriend' meme, what is the boyfriend looking at?", options: ["Another girl passing by", "A new car", "His phone", "A restaurant menu"], answer: "Another girl passing by" },
  { id: 504, category: "Memes", question: "What did the 'Grumpy Cat' meme look like?", options: ["Constantly frowning", "Smiling widely", "Sleeping", "Winking"], answer: "Constantly frowning" },
  { id: 505, category: "Memes", question: "What is the name of the Shiba Inu dog that inspired a cryptocurrency?", options: ["Cheems", "Doge", "Kabosu", "Walter"], answer: "Doge" },
  { id: 506, category: "Memes", question: "What does the 'Stonks' meme usually depict?", options: ["A dog", "A 3D rendered man in a suit", "A crying cat", "A toddler pumping his fist"], answer: "A 3D rendered man in a suit" },
  { id: 507, category: "Memes", question: "What is the context of the 'Woman Yelling at a Cat' meme?", options: ["She is allergic", "The cat stole her food", "She is yelling, the cat is eating salad", "The cat is barking"], answer: "She is yelling, the cat is eating salad" },
  { id: 508, category: "Memes", question: "Which song is heavily associated with getting 'Rickrolled'?", options: ["All Star", "Never Gonna Give You Up", "Darude Sandstorm", "Shooting Stars"], answer: "Never Gonna Give You Up" },
  { id: 509, category: "Memes", question: "In the 'Is this a pigeon?' meme, what is the guy actually pointing at?", options: ["A pigeon", "A butterfly", "A bird", "A leaf"], answer: "A butterfly" },
  { id: 510, category: "Memes", question: "What phrase does the 'Success Kid' meme usually represent?", options: ["Failing spectacularly", "Small victories", "Being angry", "Sleeping late"], answer: "Small victories" },
  { id: 511, category: "Memes", question: "What does the 'Two Buttons' meme feature?", options: ["A robot sweating", "A superhero sweating", "A monkey thinking", "A guy sweating over two red buttons"], answer: "A guy sweating over two red buttons" },
  { id: 512, category: "Memes", question: "Who is the man in the 'Roll Safe' (guy tapping his head) meme?", options: ["Kevin Hart", "Kayode Ewumi", "Eddie Murphy", "Chris Rock"], answer: "Kayode Ewumi" },
  { id: 513, category: "Memes", question: "What is the phrase associated with the dog sitting in a burning room?", options: ["This is fine", "I'm in danger", "Help me", "It's hot"], answer: "This is fine" },
  { id: 514, category: "Memes", question: "In the 'Drake Hotline Bling' meme, what is Drake doing in the top panel?", options: ["Smiling", "Pointing happily", "Turning away in disgust", "Sleeping"], answer: "Turning away in disgust" },
  { id: 515, category: "Memes", question: "What is the name of the meme where a guy blinks in surprise/confusion?", options: ["Blinking White Guy", "Surprised Pikachu", "Confused Nick Young", "Math Lady"], answer: "Blinking White Guy" },

  // FOOTBALL
  { id: 601, category: "Football", question: "Which player has won the most Ballon d'Or awards?", options: ["Cristiano Ronaldo", "Lionel Messi", "Neymar Jr", "Ronaldinho"], answer: "Lionel Messi" },
  { id: 602, category: "Football", question: "Which country won the FIFA World Cup in 2022?", options: ["France", "Argentina", "Brazil", "Croatia"], answer: "Argentina" },
  { id: 603, category: "Football", question: "How many players are on the field for one team in a standard football match?", options: ["9", "10", "11", "12"], answer: "11" },
  { id: 604, category: "Football", question: "Which football club is known as 'Los Blancos'?", options: ["FC Barcelona", "Real Madrid", "Juventus", "Bayern Munich"], answer: "Real Madrid" },
  { id: 605, category: "Football", question: "Who won the FIFA World Cup in 2018?", options: ["Brazil", "Germany", "France", "Argentina"], answer: "France" },
  { id: 606, category: "Football", question: "Which stadium is the home of FC Barcelona?", options: ["Santiago Bernabeu", "Old Trafford", "Camp Nou", "Anfield"], answer: "Camp Nou" },
  { id: 607, category: "Football", question: "What is the highest governing body of association football?", options: ["UEFA", "CONMEBOL", "FIFA", "AFC"], answer: "FIFA" },
  { id: 608, category: "Football", question: "Which country has won the most FIFA World Cups?", options: ["Germany", "Italy", "Argentina", "Brazil"], answer: "Brazil" },
  { id: 609, category: "Football", question: "Who holds the record for the most goals in a single calendar year (91 goals in 2012)?", options: ["Pele", "Cristiano Ronaldo", "Lionel Messi", "Gerd Muller"], answer: "Lionel Messi" },
  { id: 610, category: "Football", question: "Which English club is known as 'The Red Devils'?", options: ["Arsenal", "Liverpool", "Manchester United", "Chelsea"], answer: "Manchester United" },
  { id: 611, category: "Football", question: "In what year was the first FIFA World Cup held?", options: ["1920", "1930", "1940", "1950"], answer: "1930" },
  { id: 612, category: "Football", question: "Who is the all-time top scorer for the Portugal national team?", options: ["Eusebio", "Luis Figo", "Cristiano Ronaldo", "Diogo Jota"], answer: "Cristiano Ronaldo" },
  { id: 613, category: "Football", question: "Which club did Diego Maradona famously lead to two Serie A titles?", options: ["Juventus", "AC Milan", "Napoli", "Inter Milan"], answer: "Napoli" },
  { id: 614, category: "Football", question: "What is the name of the trophy awarded to the Champions League winners?", options: ["The Jules Rimet Trophy", "The European Champion Clubs' Cup", "The FA Cup", "The Copa America"], answer: "The European Champion Clubs' Cup" },
  { id: 615, category: "Football", question: "Which manager has won the most Premier League titles?", options: ["Arsene Wenger", "Pep Guardiola", "Jose Mourinho", "Sir Alex Ferguson"], answer: "Sir Alex Ferguson" },

  // SCIENCE
  { id: 701, category: "Science", question: "What is the chemical symbol for Gold?", options: ["Au", "Ag", "Gd", "Go"], answer: "Au" },
  { id: 702, category: "Science", question: "What is the powerhouse of the cell?", options: ["Nucleus", "Mitochondria", "Ribosome", "Golgi Apparatus"], answer: "Mitochondria" },
  { id: 703, category: "Science", question: "What is the main gas that makes up the Earth's atmosphere?", options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"], answer: "Nitrogen" },
  { id: 704, category: "Science", question: "What is the freezing point of water in Celsius?", options: ["0°C", "32°C", "100°C", "-1°C"], answer: "0°C" },
  { id: 705, category: "Science", question: "How long does it take for light from the Sun to reach Earth?", options: ["8 seconds", "8 minutes", "8 hours", "8 days"], answer: "8 minutes" },
  { id: 706, category: "Science", question: "What is the hardest natural substance on Earth?", options: ["Diamond", "Graphene", "Quartz", "Iron"], answer: "Diamond" },
  { id: 707, category: "Science", question: "Which planet is closest to the Sun?", options: ["Venus", "Earth", "Mercury", "Mars"], answer: "Mercury" },
  { id: 708, category: "Science", question: "What is the most abundant element in the universe?", options: ["Oxygen", "Carbon", "Hydrogen", "Helium"], answer: "Hydrogen" },
  { id: 709, category: "Science", question: "Who developed the theory of relativity?", options: ["Isaac Newton", "Nikola Tesla", "Albert Einstein", "Galileo Galilei"], answer: "Albert Einstein" },
  { id: 710, category: "Science", question: "What is the atomic number of Oxygen?", options: ["6", "7", "8", "9"], answer: "8" },
  { id: 711, category: "Science", question: "Which organ in the human body produces insulin?", options: ["Liver", "Kidney", "Pancreas", "Stomach"], answer: "Pancreas" },
  { id: 712, category: "Science", question: "What force keeps the planets in orbit around the Sun?", options: ["Magnetism", "Friction", "Gravity", "Inertia"], answer: "Gravity" },
  { id: 713, category: "Science", question: "What is the speed of light in a vacuum?", options: ["300,000 km/s", "150,000 km/s", "1,000,000 km/s", "30,000 km/s"], answer: "300,000 km/s" },
  { id: 714, category: "Science", question: "What part of the plant conducts photosynthesis?", options: ["Roots", "Stem", "Leaf", "Flower"], answer: "Leaf" },
  { id: 715, category: "Science", question: "Which blood type is known as the universal donor?", options: ["A+", "B-", "AB+", "O-"], answer: "O-" }
];
